name: "CI"

on:
  push:
    branches:
      - "master"
      - "6.x"
      - "7.10.2"
  pull_request:
    branches:
      - "master"
      - "6.x"
env:
  gradle-version: "7.5.1"
  java-version: "11"

jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Checkout repository"
        uses: "actions/checkout@v2"
      - name: "Set up JDK"
        uses: "actions/setup-java@v1"
        with:
          java-version: "${{ env.java-version }}"
      - name: "Gradle build"
        uses: "eskatos/gradle-command-action@v1"
        with:
          gradle-version: "${{ env.gradle-version }}"
          arguments: "clean build --stacktrace"
      - name: The job has failed
        if: ${{ failure() }}
        run: cat /home/runner/work/fastfilter-elasticsearch-plugin/fastfilter-elasticsearch-plugin/.gradle/reaper/*/*
      - name: "GitHub release"
        if: "contains('refs/heads/master refs/heads/6.x refs/heads/7.10.2', github.ref)"
        run: |
          version=$(cat gradle.properties | grep -e "^version *=" | awk -F" *= *" '{print $NF}')
          echo ${{ github.token }} | gh auth login --with-token
          gh release create ${version} ./build/distributions/*.zip
